### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by CAYdenberg** [Beanstream-DRWP/beanstream-php#2]
After installing via Composer and running the example code verbatim in a stand-alone index.php file I get the following error: 

Fatal error: Call to undefined function Beanstream\msgfmt_format_message() in C:\wamp\www\beanstream\vendor\beanstream\beanstream\src\Beanstream\communications\Endpoints.php on line 105

Can you help me diagnose what I'm doing wrong?

**Comment by k-nights** [comment]
Hi @CAYdenberg, 

Would you be able to confirm that you are using both PHP 5.3.0+ and PECL 1.0+?

We will be modifying these function calls to use the less-stringing `str_replace` in the very near future.

**Comment by CAYdenberg** [comment]
I am using PHP 5.4 in development. PECL appears to be disabled in my environment - not sure how typical this is.
